[project]
name = "clode"
description="A Python package for solving ordinary differential equations on the GPU using OpenCL"
dynamic = ["version"]
authors = [
    {name="Patrick Fletcher", email="patrick.allen.fletcher@gmail.com"},
]
requires-python = ">=3.8"
readme = "docs/README.md"
license = "MIT"
dependencies = [
    "numpy>=2.0.2",
    "pyopencl>=2025.2",
]

maintainers = [
    {name="Patrick Fletcher", email="patrick.allen.fletcher@gmail.com"},
    {name="Wolf Byttner", email="wolf@byttner.org"},
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Environment :: GPU",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
Documentation = "https://patrickfletcher.github.io/clODE/"
Repository = "https://github.com/patrickfletcher/clODE"

[tool.setuptools.dynamic]
version = {attr = "clode.__version__"}

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["clode", "clode.*"]
exclude = ["clode.cpp", "clode.cpp.*"]

[tool.setuptools.package-data]
clode = [
    "py.typed",
    "kernels/*.cl",
    "kernels/observers/*.clh",
    "kernels/steppers/*.clh",
]

[build-system]
requires = [
    "setuptools>=75.0.0,<81",
    "wheel",
]
build-backend = "setuptools.build_meta"
