name: CI Linux

on:
  push:
    branches:
      - main
      - github-pages
      - '*'
  pull_request:
    branches:
      - main
      - github-pages
      - '*'

jobs:
  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Update system
        run: sudo apt update

      - name: Install Dependencies
        run: sudo apt install ocl-icd-libopencl1 clinfo intel-opencl-icd

      - name: Test OpenCL
        run: clinfo

      - name: Install Dev Dependencies
        run: sudo apt install ocl-icd-opencl-dev python3-dev

      - name: Build the code
        run: bazel build //... --subcommands

      - name: Setup venv
        run: make venv

      - name: Install requirements
        run: make install

      - name: Install pip wheel
        run: make install_clode

      - name: make sdist
        run: make sdist

  deploy_docs:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/github-pages'
    needs: test_linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: requirements.txt

  publish_to_test_pypi:
    runs-on: ubuntu-22.04
    needs: test_linux
    steps:
      - uses: actions/checkout@v3

      - name: Publish to PyPI test
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: make upload

  publish_to_prod_pypi:
    if: github.ref == 'refs/heads/main'
    needs: test_linux
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: make upload_prod
