name: CI Linux

on:
  push:
    branches:
      - main
      - github-pages
      - '*'
  pull_request:
    branches:
      - main
      - github-pages
      - '*'

jobs:
  test_linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Update system
        run: sudo apt update

      - name: Install Dependencies
        run: sudo apt install ocl-icd-libopencl1 clinfo intel-opencl-icd

      - name: Test OpenCL
        run: clinfo

      - name: Install Dev Dependencies
        run: sudo apt install ocl-icd-opencl-dev python3-dev

      - name: Build the code
        run: bazel build //... --subcommands

      - name: Setup venv
        run: make venv

      - name: Install requirements
        run: make install

      - name: Install pip wheel
        run: make install_clode

      - name: make sdist
        run: make sdist

      - name: Publish to PyPI test
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}
        run: |
          make upload

      - name: Publish to PyPI
        if: github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          make upload_prod

  deploy_docs:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/github-pages'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Update system
        run: sudo apt update

      - name: Install Dependencies
        run: sudo apt install ocl-icd-libopencl1 clinfo intel-opencl-icd

      - name: Test OpenCL
        run: clinfo

      - name: Install Dev Dependencies
        run: sudo apt install ocl-icd-opencl-dev python3-dev

      - name: Setup venv
        run: make venv

      - name: Install requirements
        run: make install

      - name: Install pip wheel
        run: make install_clode

      - name: activate venv
        run: source venv/bin/activate

      - name: Build docs with mkdocs
        run: mkdocs build --clean

      - name: Create tar file of site folder
        run: tar -czvf site.tar.gz site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          artifact-name: site
          path: site.tar.gz

